version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: rinl_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinl_transport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: rinl_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/rinl_transport
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: rinl_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
